#!/usr/bin/env node
'use strict';
// Transform build/skills + agents/ + templates/ + references/ + docs/ into one directory per tool under build/{product,self}/<target>/.
const fs = require('fs');
const path = require('path');
const ROOT_REL = process.cwd();
const { SELECTED_DIR, SELECTED_SELF_DIR, TEMPLATES_DIR, ORG_DIR_SRC, REPORTS_DIR, CONTROL_PLANE_DIR, REFERENCES_DIR, DOCS_DIR, DIST_DIR, DIST_SELF_DIR, exists, rmrf, ensureDir, copyTree, render, readJson, writeJson, loadManifest, splitList } = require('./lib/fs-utils');
const { TARGETS } = require('./lib/targets');
const { indexPersonas } = require('./lib/personas');
const fm = require('./lib/frontmatter');

const START = '<!-- agent-brain:start -->';
const END = '<!-- agent-brain:end -->';
const PERSONA_ONLY_KEYS = ['skills', 'extends', 'abstract'];
// Links from a skill to the repo-root references/ (any number of ../). Rewritten to the injected copy.
const REF_LINK = /(?<![A-Za-z0-9._/-])((?:\.\.\/)+references\/([A-Za-z0-9._-]+\.md))/g;

const selfBuild = process.argv.includes('--self');
const manifest = loadManifest({ selfBuild });
const selectedDir = selfBuild ? SELECTED_SELF_DIR : SELECTED_DIR;
const distDir = selfBuild ? DIST_SELF_DIR : DIST_DIR;
const indexPath = path.join(selectedDir, 'INDEX.json');
if (!exists(indexPath)) { console.error(`${path.relative(ROOT_REL, indexPath)} not found: run \`npm run select${selfBuild ? ' -- --self' : ''}\` first`); process.exit(1); }
const { skills } = readJson(indexPath);
const personas = indexPersonas(manifest.personas).filter(p => !p.missing && !p.problems.length);
const targets = manifest.targets.filter(t => TARGETS[t]);
if (!targets.length) { console.error('manifest.json: no valid targets'); process.exit(1); }
// The organization is maintained as ordered parts under org/ and emitted as one file.
const ORG_PARTS_DIR = ORG_DIR_SRC;
const orgMd = fs.readdirSync(ORG_PARTS_DIR).filter(f => /^\d+-.*\.md$/.test(f)).sort()
  .map(f => fs.readFileSync(path.join(ORG_PARTS_DIR, f), 'utf8').trim()).join('\n\n') + '\n';
const rootRefs = new Set(exists(REFERENCES_DIR) ? fs.readdirSync(REFERENCES_DIR).filter(f => f.endsWith('.md')) : []);

const md = vars => (rel, buf) => (rel.endsWith('.md') ? render(buf.toString('utf8'), vars) : buf);

function indexMarkdown(vars) {
  const byCat = {};
  for (const s of skills) (byCat[s.category] = byCat[s.category] || []).push(s);
  const lines = ['## Installed personas and skills', '',
    `Personas: ${personas.map(p => `\`${p.name}\``).join(', ')}. Read your persona before acting; use only the skills it lists.`, '',
    `Skills live in \`${vars.SKILLS_DIR}/\`:`, ''];
  for (const cat of Object.keys(byCat).sort()) lines.push(`- **${cat}**: ${byCat[cat].map(s => `\`${s.name}\``).join(', ')}`);
  return lines.join('\n') + '\n';
}

function alwaysOnContent(target, vars) {
  const body = [START, '<!-- Generated by agent-brain. Do not edit inside this block; edit the parts under org/ and rebuild. -->', '',
    render(orgMd, vars).trim(), '', indexMarkdown(vars).trim(), '', END, ''].join('\n');
  return target.alwaysOn.kind === 'mdc'
    ? `---\ndescription: agent-brain organization and rules (always on)\nalwaysApply: true\n---\n\n${body}`
    : body;
}

function personaBody(p, vars) {
  const d = p.resolvedData;
  const header = (p.skills.length ? `> Skills this persona may use: ${p.skills.map(s => `\`${s}\``).join(', ')} (in \`${vars.SKILLS_DIR}/\`). No others.\n` : '')
    + `> Model and effort are not fixed for this role: the EM chooses them per task from complexity, budget, and provider quota, and the control plane records what ran (\`${vars.ORG_DIR}/control-plane/\`).\n`;
  return header + render(p.resolvedBody, vars);
}

for (const id of targets) {
  const target = TARGETS[id];
  const out = path.join(distDir, id);
  rmrf(out);
  ensureDir(out);
  const O = manifest.orgDir;
  const vars = {
    TOOL: target.toolLabel || target.label,
    ORG_DIR: O,
    SKILLS_DIR: target.skillsDir,
    AGENTS_DIR: target.agentsDir || '',
    AGENTS_NOTE: target.agentsDir
      ? `\`${target.agentsDir}/\` (subagents, one per persona except the CEO) and \`${target.skillsDir}/<persona>/\` (same content as a skill)`
      : `\`${target.skillsDir}/<persona>/\` (no subagents in this tool; adopt the persona skill in the same session)`,
    PM_TOOL: manifest.projectManagement || 'the configured tracker',
    DELEGATION_NOTE: '',
    ROUTING_NOTE: target.routingNote || '',
    SPAWN_MODE: target.spawn || 'main-only',
  };
  vars.DELEGATION_NOTE = render(target.delegationNote, vars);
  const files = [];
  const seeds = [];
  const put = (rel, content, seed = false) => { const p = path.join(out, rel); ensureDir(path.dirname(p)); fs.writeFileSync(p, content); (seed ? seeds : files).push(rel); };
  const refDirFor = skillRel => path.posix.relative(skillRel, `${O}/references`);

  // 1. Skills: flat <skillsDir>/<name>/; placeholders rendered; links to repo-root references/ rewritten to the injected copy.
  for (const s of skills) {
    const dest = `${target.skillsDir}/${s.name}`;
    const written = copyTree(path.join(selectedDir, s.category, s.name), path.join(out, dest), (rel, buf) => {
      if (rel === 'mcp.json') return null;
      if (!rel.endsWith('.md')) return buf;
      const fileDir = path.posix.join(dest, path.posix.dirname(rel));
      return render(buf.toString('utf8'), vars).replace(REF_LINK, (m, whole, file) => (rootRefs.has(file) ? `${refDirFor(fileDir)}/${file}` : m));
    });
    for (const rel of written) files.push(`${dest}/${rel}`);
  }

  // 2. Personas: always as a skill directory; additionally as a subagent where the tool has them (never the CEO).
  for (const p of personas) {
    const d = p.resolvedData;
    put(`${target.skillsDir}/${p.name}/SKILL.md`, fm.stringify({ name: p.name, description: d.description }, personaBody(p, vars)));
    if (target.agentsDir && p.name !== 'ceo') {
      const agentData = target.agentFrontmatter({ ...d, name: p.name });
      for (const k of PERSONA_ONLY_KEYS) if (!(k in agentData)) delete agentData[k];
      put(`${target.agentsDir}/${target.agentFile(p.name)}`, fm.stringify(agentData, personaBody(p, vars)));
    }
  }

  // 3. Organization: ORG.md, templates, references, docs, control plane → <orgDir>/. Global docs and services are seeds.
  put(`${O}/ORG.md`, render(orgMd, vars));
  for (const rel of copyTree(REPORTS_DIR, path.join(out, O, 'agents-reports'), md(vars))) files.push(`${O}/agents-reports/${rel}`);
  for (const rel of copyTree(path.join(TEMPLATES_DIR, 'service-docs'), path.join(out, O, 'service-docs-template'), md(vars))) files.push(`${O}/service-docs-template/${rel}`);
  for (const rel of copyTree(path.join(TEMPLATES_DIR, 'global-docs'), path.join(out, O, 'docs'), md(vars))) seeds.push(`${O}/docs/${rel}`);
  // The control plane is code plus a schema. Its SQLite database is created on first use and is
  // never shipped or overwritten, so every file here is owned rather than seeded.
  for (const rel of copyTree(CONTROL_PLANE_DIR, path.join(out, O, 'control-plane'), md(vars))) files.push(`${O}/control-plane/${rel}`);
  for (const rel of copyTree(REFERENCES_DIR, path.join(out, O, 'references'), md(vars))) files.push(`${O}/references/${rel}`);
  for (const f of ['persona-anatomy.md']) {
    const p = path.join(DOCS_DIR, f);
    if (exists(p)) put(`${O}/docs/library/${f}`, render(fs.readFileSync(p, 'utf8'), vars));
  }
  put(`${O}/services/README.md`, `# Services\n\nOne folder per service, owned by its EM, created from \`${O}/service-docs-template/\`:\n\n\`\`\`bash\ncp -r ${O}/service-docs-template ${O}/services/<service>\n\`\`\`\n`, true);

  // 4. Session entry command: one command per harness that claims a role and loads the organization.
  if (target.commands) {
    const cmdDir = path.join(TEMPLATES_DIR, 'commands');
    for (const file of exists(cmdDir) ? fs.readdirSync(cmdDir).filter(f => f.endsWith('.md')) : []) {
      const name = file.replace(/\.md$/, '');
      const raw = render(fs.readFileSync(path.join(cmdDir, file), 'utf8'), { ...vars, TOOL_ID: id });
      const description = 'Load the agent organization and claim a role for this session (default: ceo)';
      const argumentHint = '[role] [instruction]';
      const rel = `${target.commands.dir}/${target.commands.file(name)}`;
      put(rel, target.commands.write(name, description, raw.trim(), argumentHint));
    }
  }

  // 5. Always-on file (managed block).
  put(target.alwaysOn.path, alwaysOnContent(target, vars));

  // 5b. Automatic usage capture: the harness calls control-plane/hook.js, which turns real runtime
  // facts (transcript usage, tool outcomes, turn boundaries) into events. Without this, tokens and
  // cost stay UNKNOWN until something emits them.
  if (target.hooks) put(target.hooks.file, JSON.stringify({ [target.hooks.key]: target.hooks.build(O) }, null, 2) + '\n');

  // 6. MCP servers contributed by tool skills, written in the tool's own config shape and env-var syntax.
  if (target.mcp) {
    const servers = {};
    for (const s of skills) {
      const p = path.join(selectedDir, s.category, s.name, 'mcp.json');
      if (exists(p)) Object.assign(servers, readJson(p).mcpServers || {});
    }
    if (Object.keys(servers).length) {
      const shaped = {};
      for (const [name, srv] of Object.entries(servers)) {
        const out = target.mcp.server(srv);
        if (out.headers) out.headers = Object.fromEntries(Object.entries(out.headers).map(([k, v]) => [k, String(v).replace(/\$\{([A-Z0-9_]+)\}/g, (m, e) => target.mcp.envRef(e))]));
        shaped[name] = out;
      }
      put(target.mcp.file, JSON.stringify({ ...(target.mcp.extra || {}), [target.mcp.key]: shaped }, null, 2) + '\n');
    }
  }

  writeJson(path.join(out, 'agent-brain.build.json'), {
    target: id, builtAt: new Date().toISOString(), orgDir: O,
    alwaysOn: target.alwaysOn.path, mcpFile: target.mcp ? target.mcp.file : null, mcpKey: target.mcp ? target.mcp.key : null,
    hooksFile: target.hooks ? target.hooks.file : null, hooksKey: target.hooks ? target.hooks.key : null,
    // A harness that only discovers commands under a home directory needs one extra install step
    // after injection; injection reads this to perform or print it.
    commands: target.commands ? {
      dir: target.commands.dir, scope: target.commands.scope || 'repo',
      homeEnv: target.commands.homeEnv || null, home: target.commands.home || null,
      installDir: target.commands.installDir || null, why: target.commands.why || null,
    } : null,
    files: [...new Set(files)].sort(), seeds: [...new Set(seeds)].sort(),
  });
  console.log(`  ${id.padEnd(12)} ${files.length} files + ${seeds.length} seeds → ${path.relative(ROOT_REL, path.join(distDir, id))}/`);
}
console.log(`\nbuilt ${targets.length} target(s) · ${skills.length} skills · ${personas.length} personas${selfBuild ? ' (self build: includes the brain-development artifacts)' : ''}`);
